Comments keywords header fields
datawookie/emayili pull request #88
Opened 2021-10-12 07:15 UTC by Swechhya

This PR addresses #85.

Test email screenshot
![Screen Shot 2021-10-13 at 12 07 48](https://user-images.githubusercontent.com/6251412/137079449-fe0a3bb2-57e0-4d32-8b4c-afcdd402288a.png)
:

2021-10-12 07:16 UTC, Swechhya commented
@datawookie Added this PR for #85. Let me know if anything is to be changed. Thanks!

2021-10-12 08:24 UTC, datawookie requested changes
This is great. Thank you!

Have you tested that you can send a message with comments and/or keywords?

2021-10-12 08:24 UTC, datawookie commented on R/header-mail.R
> +#' library(magrittr)
I don't think that it's necessary to explicitly include `{magrittr}` anymore since the `%>%` is exported from the `{emayili}` namespace.

2021-10-12 08:24 UTC, datawookie commented on R/header-mail.R
> +#' library(magrittr)
I don't think that it's necessary to explicitly include `{magritt}` anymore since the `%>%` is exported from the `{emayili}` namespace.

2021-10-12 08:24 UTC, datawookie commented on R/header-mail.R
> +#' envelope() %>% keywords("keyword1, keyword2")
How about some less generic keywords? :)

2021-10-12 08:24 UTC, datawookie commented on R/header-mail.R
> +#' # Create a message and set the keywords
Can you please terminate comment with a `.`?

2021-10-12 08:24 UTC, datawookie commented on R/header-mail.R
> +#' # Retrieve the keywords for a message
Can you please terminate comment with a `.`?

2021-10-12 08:24 UTC, datawookie commented on R/header-mail.R
> +#' # Create a message and set the comments
Can you please terminate comment with a `.`?

2021-10-12 08:24 UTC, datawookie commented on R/header-mail.R
> +#' # Retrieve the comments for a message
Can you please terminate comment with a `.`?

2021-10-13 06:33 UTC, Swechhya commented
@datawookie Updated the PR and also added a screenshot of the test mail.

2021-10-13 08:49 UTC, datawookie requested changes
Hi @Swechhya, sorry, I should have mentioned these items before. Appreciate your patience with this. We're going to make this a really good merge request! :) I have another suggestion: how about adding some tests for these functions? I've been trying to keep the test coverage at 100% and it would be excellent if these new functions were also covered. Take a look at `test-header-various.R` to get an idea of what the tests look like. They're really simple but useful. For your two functions I guess you'd want to be testing each of the functionalities which you have demonstrated in the examples (how to add multiple comments or keywords). Thanks, Andrew.

PS. One last thing: Please add your name and details to `DESCRIPTION`.

2021-10-13 08:49 UTC, datawookie commented on R/header-mail.R
> +    header_get(msg, "comments")
Please capitalise `Comments` for consistency with other field names.

2021-10-13 08:49 UTC, datawookie commented on R/header-mail.R
> +    msg <- header_set(msg, "comments", comments, append = FALSE)
Please capitalise `Comments` for consistency with other field names.

2021-10-13 08:49 UTC, datawookie commented on R/header-mail.R
> +    header_get(msg, "keywords")
Please capitalise `Keywords` for consistency with other field names.

2021-10-13 08:49 UTC, datawookie commented on R/header-mail.R
> +    msg <- header_set(msg, "keywords", arguments, append = append, sep = ", ")
Please capitalise `Keywords` for consistency with other field names.

2021-10-13 08:53 UTC, datawookie commented on R/header-mail.R
> +#' @seealso \code{\link{to}}, \code{\link{from}}, \code{\link{cc}}, \code{\link{bcc}} and \code{\link{reply}}
I wonder if these topics are really relevant here? The participants in the email are not really related to the comments. Thoughts?

2021-10-14 04:19 UTC, Swechhya commented on R/header-mail.R
> +#' @seealso \code{\link{to}}, \code{\link{from}}, \code{\link{cc}}, \code{\link{bcc}} and \code{\link{reply}}
@datawookie Maybe `subject` would be closely related. Should I change this to subject?

2021-10-14 05:02 UTC, Swechhya commented
@datawookie  Updated the documentation and added tests. Please let me know if anything is amiss.

2021-10-14 07:32 UTC, datawookie commented
> amiss

Thank you! This is one of my favourite words! :)

2021-10-14 07:39 UTC, datawookie requested changes
Sorry, a few more requests. Thanks for your patience with this! :pray:

2021-10-14 07:39 UTC, datawookie commented on tests/testthat/test-header-various.R
> +  expect_equal(comments(msg), "Test message")
Maybe test with `as.character()` and then use `expect_match()` to check if `Comment:` and the actual comments are included? See, for example, tests for `inreplyto()`.

2021-10-14 07:39 UTC, datawookie commented on tests/testthat/test-header-various.R
> +  expect_match(
Can we also have a test of keywords retrieval using `keywords()` (like the test you currently have for `comments()`)?

2021-10-14 07:39 UTC, datawookie commented on R/header-mail.R
> +
Delete this empty line, please! :)

2021-10-14 07:39 UTC, datawookie commented on R/header-mail.R
> +
Delete this empty line, please! :)

2021-10-14 09:29 UTC, datawookie commented
@Swechhya please also take a look at [this](https://github.com/datawookie/emayili/runs/3890571512?check_suite_focus=true).

2021-10-14 09:51 UTC, Swechhya commented
> @Swechhya please also take a look at [this](https://github.com/datawookie/emayili/runs/3890571512?check_suite_focus=true).
 @datawookie This should have been fixed in commit https://github.com/datawookie/emayili/pull/88/commits/7cc0be56a02fcd424652c8856b061e88d0efc23a
 
 Also, pushed changes as per the latest comment. Please let me know if there is anything else that I have missed.

2021-10-22 05:47 UTC, closed without merging